site_name: U.S. Cellular How To

pages:
  - Introduction: index.md
  - Catalog of How Tos:
    - USCC Engineering Organization Access: uscc-organization.md
    - Generate SSH Key pair: generate-ssh-key.md
    - Version Control:
      - Day to Day Git: version_control/daytoday.md
      - Add a File to Git: version_control/add_file.md
      - Create a Repository: version_control/create-repo.md
      - Clone a Repository: version_control/clone-repo.md
      - Create Branches: version_control/create-branch.md
      - Commit Changes: version_control/commit.md
      - Push Commits: version_control/push.md
      - Pull/Fetch: version_control/pull.md
      - Fetch a Remote created Branch: version_control/fetch_branches.md
      - Checkout Branch: version_control/checkout.md
      - Stash/Shelve changes: version_control/stashing.md
  - Worflows: workflow-strategy.md
  - Automation Summit: auto-summit.md